DROP TABLE CLIENTE;
CREATE TABLE CLIENTE(
    ID_CLIENTE INTEGER PRIMARY KEY,
    NOME_CLIENTE VARCHAR(50) NOT NULL,
    IDADE_CLIENTE INTEGER NOT NULL,
    CPF_CLIENTE VARCHAR(15) NOT NULL,
    EMAIL_CLIENTE VARCHAR(30) NOT NULL,
    ENDERECO_CLIENTE VARCHAR(80) NOT NULL
);
SELECT * FROM CLIENTE;
    
CREATE TABLE BICICLETA(
    ID_BICICLETA INTEGER PRIMARY KEY,
    MODELO_BICICLETA VARCHAR(20) NOT NULL,
    MARCA_BICICLETA VARCHAR(20) NOT NULL,
    ANO_BICICLETA INTEGER NOT NULL,
    PRECO_BICICLETA INTEGER NOT NULL,
    NUMERO_SERIE_BICICLETA VARCHAR(20) NOT NULL,
    TIPO_BICICLETA VARCHAR(30) NOT NULL,
    ID_CLIENTE INTEGER REFERENCES CLIENTE (ID_CLIENTE)
);
SELECT * FROM BICICLETA;
    
CREATE TABLE TELEFONE(
    TELEFONE_BICICLETA VARCHAR(40) NOT NULL,
    ID_CLIENTE INTEGER REFERENCES CLIENTE (ID_CLIENTE)
);
SELECT * FROM TELEFONE;
    
CREATE TABLE VISTORIA(
    ID_VISTORIA INTEGER PRIMARY KEY,
    DATA_VISTORIA DATE NOT NULL,
    ID_BICICLETA INTEGER REFERENCES BICICLETA (ID_BICICLETA)
);
SELECT * FROM VISTORIA;

CREATE TABLE IMAGEM(
    ID_IMAGEM INTEGER PRIMARY KEY,
    TIPO_IMAGEM CHAR(1) NOT NULL,
    IMAGEM INTEGER NOT NULL,
    ID_VISTORIA INTEGER REFERENCES VISTORIA (ID_VISTORIA)
);
SELECT * FROM IMAGEM;

CREATE TABLE SEGURO(
    TIPO_SEGURO VARCHAR(20) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_TERMINO DATE NOT NULL,
    APOLICE INTEGER NOT NULL,
    ID_BICICLETA INTEGER REFERENCES BICICLETA (ID_BICICLETA)
);
SELECT * FROM SEGURO;

CREATE TABLE PAGAMENTO(
    ID_PAGAMENTO INTEGER PRIMARY KEY,
    DATA_PAGAMENTO DATE,
    VALOR_PAGAMENTO INTEGER,
    ID_BICICLETA INTEGER REFERENCES BICICLETA (ID_BICICLETA)  
);
SELECT * FROM PAGAMENTO;
